<footer>
<span>Todos Direitos Reservados - 2021</span>
</footer>

<script src="src/js/cookies.js"></script>
<script src="src/js/jquery.min.js"></script>
<script src="src/js/jquery.js"></script>
<script src="src/js/all.min.js"></script>
<script src="src/js/scripts.js"></script>


<!-- JS Bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
