<footer>
<span>Todos Direitos Reservados - 2021</span>
</footer>

<script src="src/js/all.min.js"></script>
<script src="src/js/scripts.js"></script>
<script src="https://cdn.tiny.cloud/1/60xobe09a2ftk9t3vs8hz0h0ltzbqatf82xwi6g3gvdthm8n/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script src="src/js/tinymce.js"></script>

<!-- JS Bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
