<?php include 'header.phtml'?>

<main>
  <div class="container-gereciar-noticia">
    <h2>Gerenciar notícias</h2>

  <?php foreach($noticias as $noticia) {?>
    <article id="<?= $noticia->id ?>" id_noticia="<?= $noticia->id ?>">

            <div class="item-img">
                <img src="<?= $noticia->thumbnail ?>" alt="Imagem-capa">
            </div>

            <div class="conteudo-texto-item">
                <a href="<?= PATH_INDEX ?>noticia?id=<?= $noticia->id ?>"><h3><?= $noticia->titulo ?></h3></a>
                <p><?= $noticia->descricao ?></p>
            </div>
            <div class="icons-gerenciar">
                  <a class="botao_deletar_noticia" title="apagar" id_noticia="<?= $noticia->id ?>">
                    <i class="fas fa-trash"></i>
                  </a>
                  <a href="<?= PATH_INDEX ?>edit?id=<?= $noticia->id ?>" title="editar">
                    <i class="fas fa-pen"></i>
                  </a>
                  
            </div>
        </article>

      <?php } ?>
    
  </div>
</main>

<?php include 'footer.phtml' ?>
<script src="./public/js/deletarNoticia.js"></script>