<?php include 'header.phtml'?>

<main>
  <div class="container-gereciar-noticia">
    <h2>Gerenciar notícias</h2>

  <?php foreach($dados['noticias'] as $dado) {?>
    <article id="<?=$dado->id?>" id_noticia="<?=$dado->id?>">

            <div class="item-img">
                <img src="<?=$dado->thumbnail?>" alt="Imagem-capa">
            </div>

            <div class="conteudo-texto-item">
                <a href="<?=PATH_INDEX?>noticia?id=<?=$dado->id?>"><h3><?=$dado->titulo?></h3></a>
                <p><?=$dado->descricao?></p>
            </div>
            <div class="icons-gerenciar">
                  <a class="botao_deletar_noticia" title="apagar" id_noticia="<?=$dado->id?>">
                    <i class="fas fa-trash"></i>
                  </a>
                  <a href="<?=PATH_INDEX?>edit?id=<?=$dado->id?>" title="editar">
                    <i class="fas fa-pen"></i>
                  </a>
                  
            </div>
        </article>

      <?php } ?>
    
  </div>
</main>

<?php include 'footer.phtml' ?>
<script src="./public/js/deletarNoticia.js"></script>