<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./public/css/styles.css">

    <!--Fontawesome CSS -->
    <link rel="stylesheet" href="./public/css/all.min.css" >

    <!--Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

    <title><?=$dados['titulo']?></title>
</head>
<header>
        <span>Dentro da Informação</span>


<nav>
        <ul>
            <li><a href="<?=PATH_INDEX?>home">Home</a></li>
            <li><a href="<?=PATH_INDEX?>contato">Contato</a></li>
            <li><a href="<?=PATH_INDEX?>sobre">Sobre</a></li>
            <li><a href="<?=PATH_INDEX?>admin-login">ADM</a></li>
        </ul>
<nav>
</header> 