<di class="conteiner-home">
    <main>

    <h2 class="titulo-main">Últimas Notícias</h2>
        <article>
            <div class="item-img">
                <img src="resources/images/Karol.jpg" alt="Karol">
            </div>

            <div class="conteudo-texto-item">
                <h3>Karol Conká sai do BBB</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et dolorum veritatis laborum dicta natus nesciunt, molestiae quaerat esse dolores perferendis porro velit quasi eum amet quidem tenetur dolor numquam illum.</p>
            </div>
        </article>

        <article>
            <div class="item-img">
                <img src="resources/images/Karol.jpg" alt="Karol">
            </div>

            <div class="conteudo-texto-item">
                <h3>Karol Conká sai do BBB</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et dolorum veritatis laborum dicta natus nesciunt, molestiae quaerat esse dolores perferendis porro velit quasi eum amet quidem tenetur dolor numquam illum.</p>
            </div>
        </article>

        <article>
            <div class="item-img">
                <img src="resources/images/Karol.jpg" alt="Karol">
            </div>

            <div class="conteudo-texto-item">
                <h3>{{titulo_noticia}}</h3>
                <p>{{descricao_noticia}}</p>
            </div>
        </article>

        <article>
            <div class="item-img">
                <img src="resources/images/Karol.jpg" alt="Karol">
            </div>

            <div class="conteudo-texto-item">
                <h3>Karol Conká sai do BBB</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et dolorum veritatis laborum dicta natus nesciunt, molestiae quaerat esse dolores perferendis porro velit quasi eum amet quidem tenetur dolor numquam illum.</p>
            </div>
        </article>

    </main>
    <aside>
        <h2 class="titulo-main">Em Destaque</h2>
    </aside>
</div>