
<?php include 'header.phtml' ?>

<div class="conteiner-home">
    <main>

    <h2 class="titulo-main">Últimas Notícias</h2>

    <?php foreach($dados['noticias'] as $dado){ ?>
        <article>
            <div class="item-img">
                <img src="<?=$dado->thumbnail?>" alt="Karol">
            </div>

            <div class="conteudo-texto-item">
                <a href="<?=PATH_INDEX?>noticia?slug=<?=$dado->slug?>"><h3><?=$dado->titulo?></h3></a>
                <p><?=$dado->descricao?></p>
            </div>
        </article>
    <?php } ?>
        <span><a class="link todas-noticias" href="<?=PATH_INDEX?>todas-noticias">Todas Notícias?</a></span>
    </main>
    <aside>
        <h2 class="titulo-main">Em Destaque</h2>
    </aside>
</div>

<?php include 'footer.phtml' ?>