<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"href="src/css/homeestilo.css">
    <title>Dentro da informação</title>
</head>
<body>
    <div class="container" id="cabecalho">
        <p>Dentro da informação</p>
    </div>
    <div class="conteiner" id="divdireita">
        <h2>Últimas Notícias</h2>
    </div>
    <div class="container" id="divesquerda"></div>
    <div class="container" id="divdireita2"></div>
    <div class="container"></div>
    <footer id="rodape"></footer>
</body>
</html>