
<?php require_once 'header.phtml' ?>
<body>
<div class="conteiner-home">
    <main>

    <h2 class="titulo-main">Últimas Notícias</h2>

    <?php if(is_string($dados['total_noticias'])){ echo $dados['total_noticias'];} ?>

    <?php foreach($dados['noticias'] as $dado){ ?>
        
        <article>
            <div class="item-img">
                <img src="<?=$dado->thumbnail?>" alt="Imagem-capa">
            </div>

            <div class="conteudo-texto-item">
                <a href="<?=PATH_INDEX?>noticia?id=<?=$dado->id?>"><h3><?=$dado->titulo?></h3></a>
                <p><?=$dado->descricao?></p>
            </div>
        </article>

    <?php } ?>

        <span><a class="link todas-noticias" href="<?=PATH_INDEX?>todas-noticias">Todas Notícias?</a></span>
    </main>
    <aside>
        <h2 class="titulo-main">Em Destaque</h2>

        <?php foreach($dados['noticias_destaque'] as $dado){ ?>

        <article>
            <div class="item-img">
                <img src="<?=$dado['thumbnail']?>" alt="Imagem-capa">
            </div>

            <div class="conteudo-texto-item">
                <a href="<?=PATH_INDEX?>noticia?id=<?=$dado['id']?>"><h3><?=$dado['titulo']?></h3></a>
                <p><?=$dado['descricao']?></p>
            </div>
        </article>

        <?php } ?>

    </aside>
</div>
</body>

<?php require_once 'footer.phtml' ?>