<article>
<div class="item-img">
<img src="{{thumbnail}}" alt="Karol">
</div>

<div class="conteudo-texto-item">
    <h3>Karol conká sai do BBB</h3>
    <hr>
    <p>hoje depois de uma votação acirrada...</p>
</div>


</article>

<article>
<div class="item-img">
<img src="resources/images/Karol.jpg" alt="Karol">
</div>

<div class="conteudo-texto-item">
    <h3>Karol conká sai do BBB</h3>
    <hr>
    <p>hoje depois de uma votação acirrada...</p>
</div>


</article>

<article>
<div class="item-img">
<img src="resources/images/Karol.jpg" alt="Karol">
</div>

<div class="conteudo-texto-item">
    <h3>Karol conká sai do BBB</h3>
    <hr>
    <p>hoje depois de uma votação acirrada...</p>
</div>


</article>