
<?php include 'header.phtml' ?>

<main class="conteiner-noticia"> 

    <h1 class="titulo-noticia"><?=$dados['noticia']->titulo?></h1>
    <p><?=$dados['noticia']->descricao?></p>
    <hr>
    <span class="data-publicacao">Publicado em <?=$dados['noticia']->data_formatada?>, por <?=$dados['noticia']->nome?></span>

    <div class="conteudo-noticia">

        <p><?=$dados['noticia']->texto_conteudo?></p>

    </div>
    
</main>

<hr>

<section class="container-avaliar-noticia">
  <h3>Avalie esta notícia!</h3>

  <textarea id="comentario_avaliacao">comentário... (Opcional)</textarea>

  <h3>Nota: </h3>
  <select id="nota_avaliacao">
    <option value="">Avalie</option>
    <option value="1">1 - muito ruim</option>
    <option value="2">2 - ruim</option>
    <option value="3">3 - boa</option>
    <option value="4">4 - muito boa</option>
    <option value="5">5 - ótima</option>
  </select>
  <button id="enviarAvaliacao">Enviar</button>

</section>




<footer class="footer-noticia">
<span>Todos Direitos Reservados - 2021</span>
</footer>
<script src="src/js/all.min.js"></script>
<script src="src/js/scripts.js"></script>
<script src="src/js/jquery.min.js"></script>
<script src="src/js/jquery.js"></script>
<script src="https://cdn.tiny.cloud/1/60xobe09a2ftk9t3vs8hz0h0ltzbqatf82xwi6g3gvdthm8n/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script src="src/js/tinymce.js"></script>