<?php include 'header.phtml'?>

<main class="conteiner-painel">
    <a href="<?=PATH_INDEX?>sair"><i class="fas fa-sign-out-alt" title="Sair"></i></a>

    <h2>Painel - HOME</h2>
    <hr>
    
    <div class="info-noticias">
        <span>Info - Noticias</span>
        <ul>
            <li><h5>Total de Noticias</h5>
                <p><?=$dados['totalNoticias']['totalNoticias']?></p>
            </li>
            <li>
                <h5>Noticias de hoje</h5>
                <p><?=$dados['noticiasHoje'][0]['noticiasHoje']?></p>
            </li>
            <li><h5>Noticias dessa semana</h5></li>
        </ul>
    </div>

    <span>Gerenciar Noticias</span>
    <section>
        <a class="btn btn-success" href="<?=PATH_INDEX?>adicionar-noticia">Incluir noticia</a>

        <a class="btn btn-primary" href="<?=PATH_INDEX?>gerenciar-noticias">Gerenciar Notícias</a>

        <div class="form-painel">
    </section>
    

    </div>
</main>

<?php include 'footer.phtml'?>
