<?php include 'header.phtml'?>

<main class="conteiner-painel">
    <h2>Painel - HOME</h2>
    <hr>
    
    <div>
        <span>Info - Noticias</span>
        <ul>
            <li><h5>Total de Noticias</h5></li>
            <li><h5>Noticias de hoje</h5></li>
            <li><h5>Noticias dessa semana</h5></li>
        </ul>
    </div>
    <div class="form-painel">

    </div>
</main>

<?php include 'footer.phtml'?>
