<?php include 'header.phtml' ?>

<body class="body-sobre">
        
      <fieldset id="oquesomos">
         <legend>O que somos?</legend>
            <p class="texto-sobre"> Dentro da informação foi  criado  em  maio de 2021 , que tem  o principal objetivo de  suprir a necessidade de usuarios  que  tem a  curiosidade de noticias e informações  prontas e atualizadas diariamente com os principais  acontecimentos do Brasil e do mundo .O nosso principal objetivo é trazer as pricipais notícias para você de forma rapida e eficiente  trazendo informações  e  visando  de forma eficiente  para você, a  nossa empresa pretende ser reconhecida  no mercado e  conhecida pela sociedade, 
Visando  na qualidade  de produto e serviço  e respeito ao cliente acima de tudo.
</p>
      </fieldset> 

</body>
    <?php include 'footer.phtml' ?>
</html>