
<?php include 'header.phtml' ?>
<div class="container-todas-noticias">

  <h2>Todas Notícias</h2>


    <?php foreach($dados['noticias'] as $dado) {?>
      <article>
            <div class="item-img">
                <img src="<?=$dado->thumbnail?>" alt="Imagem-capa">
            </div>

            <div class="conteudo-texto-item">
                <a href="<?=PATH_INDEX?>noticia?id=<?=$dado->id?>"><h3><?=$dado->titulo?></h3></a>
            </div>
        </article>

      <?php } ?>

      <div id="pagination" pageAtual="<?=$dados['pageAtual']?>">
        <?php for($i=1 ; $i <= $dados['pages']; $i++) { ?>

          <a id="page_<?=$i?>" href="<?=PATH_INDEX?>todas-noticias?page=<?=$i?>"><?=$i?></a>

        <?php } ?>
      </div>

</div>

<?php include 'footer.phtml' ?>