
<?php include 'header.phtml' ?>
<div class="container-todas-noticias">

  <h2>Todas Notícias</h2>


    <?php foreach($noticias as $noticia) {?>
      <article>
            <div class="item-img">
                <img src="<?= $noticia->thumbnail ?>" alt="Imagem-capa">
            </div>

            <div class="conteudo-texto-item">
                <a href="<?= PATH_INDEX ?>noticia?id=<?= $noticia->id ?>"><h3><?= $noticia->titulo ?></h3></a>
            </div>
        </article>

      <?php } ?>

      <div id="pagination" pageAtual="<?= $pageAtual ?>">
        <?php for($i=1 ; $i <= $pages; $i++) { ?>

          <a id="page_<?= $i ?>" href="<?= PATH_INDEX ?>todas-noticias?page=<?= $i ?>"><?= $i ?></a>

        <?php } ?>
      </div>

</div>

<?php include 'footer.phtml' ?>